stages:
  - lint
  - test
  - build
  - deploy
  - release

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/
    - .npm/

lint:
  stage: lint
  image: node:16
  script:
    - npm install
    - npm run lint
  only:
    - merge_requests
    - master

unit_tests:
  stage: test
  image: node:16
  script:
    - npm install
    - npm test
  only:
    - merge_requests
    - master

frontend_build:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build:frontend
  artifacts:
    paths:
      - build/
  only:
    - merge_requests
    - master
  parallel:
    matrix:
      - FRONTEND_BUILD: "true"

deploy_staging:
  stage: deploy
  image: node:16
  script:
    - npm run deploy:staging
  only:
    - merge_requests
    - master
  environment:
    name: staging
    url: https://staging.yourdomain.com
  variables:
    NODE_ENV: staging
    API_URL: https://staging-api.yourdomain.com

deploy_production:
  stage: deploy
  image: node:16
  script:
    - npm run deploy:production
  only:
    - master
  when: manual
  environment:
    name: production
    url: https://yourdomain.com
  variables:
    NODE_ENV: production
    API_URL: https://api.yourdomain.com

release:
  stage: release
  image: node:16
  script:
    - npm run release
  only:
    - tags
  environment:
    name: release
    url: https://releases.yourdomain.com
  variables:
    NODE_ENV: release
    API_URL: https://release-api.yourdomain.com
